### ISSUE TITLE
BUG: Problem with reachable tiles algorithim or similar.

### ISSUE THREAD

**Issue by EvieTwosday** [RadicalOyster/Godot-Tactical-RPG-Movement-Expanded#1]
In testing with a customized version and then the original, when a unit is to the right of a 'more expernsive movement tile' (ie the bush) it can only move one tile to the right, no matter what. The picture below displays this, the green unit should clearly be able to move farther right.

![TRPG_bug](https://user-images.githubusercontent.com/108846714/177673208-5d62fad4-70b5-4baf-af88-dad4305bd1bf.jpg)

edit: sorry im new to Github and don't know how to tag this post as a bug.

**Comment by RadicalOyster** [comment]
Hi, thanks for bringing this to my attention. The issue was with a few lines of missing code in the PriorityQueue class that caused some nodes to be inserted in the wrong order. I've fixed this bug in the latest commit and you can compare changes in the PriorityQueue.gd file to see what went wrong.
